apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    api.staging.int.fcubelab.com:53 {
      hosts {
        31.59.131.47 api.staging.int.fcubelab.com
      }
      cache
    }

    api.staging.int.wordflashy.com:53 {
      hosts {
        31.59.131.47 api.staging.int.wordflashy.com
      }
      cache
    }

    tekton.int.wordflashy.com:53 {
      hosts {
        31.59.131.47 tekton.int.wordflashy.com
      }
      cache
    }
    
    api.staging-gsh.int.getspeakhub.com:53 {
      hosts {
        31.59.131.47 api.staging-gsh.int.getspeakhub.com
      }
      cache
    }

    # Varsayılan K8s DNS ayarları
    .:53 {
      errors
      health
      ready
      kubernetes cluster.local in-addr.arpa ip6.arpa {
        pods insecure
        fallthrough in-addr.arpa ip6.arpa
      }
      forward . /etc/resolv.conf
      cache 30
      loop
      reload
      loadbalance
    }
