apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . }}-config
data:
  PRIMARY_HOST: "{{ .Values.primaryHost }}"
  REPLICA_HOST: "{{ .Values.replicaHost }}"
  postgresql.conf: |
    listen_addresses = '*'
    max_connections = 100
    shared_buffers = 128MB
    wal_level = replica
    max_wal_senders = 3
    max_replication_slots = 10
    wal_keep_size = 64MB
    hot_standby = on
  pg_hba.conf: |
    local   all             all                                    trust
    host    all             all             0.0.0.0/0              trust
    host    replication     postgres        0.0.0.0/0              trust
    host    api-gw          postgres        0.0.0.0/0              trust
