apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}-config
  labels:
    app: {{ .Chart.Name }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.config.scrape_interval }}

    scrape_configs:
      - job_name: '{{ .Values.config.job_name }}'
        static_configs:
          - targets: {{ toYaml .Values.config.targets | nindent 12 }}
