apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apigw-staging-cert
  namespace: staging
spec:
  secretName: apigw-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: apigw.staging.wordflashy.com
  dnsNames:
    - apigw.staging.wordflashy.com
