replicaCount: 1

image:
  repository: ghcr.io/burakbalim/api-gw
  pullPolicy: Always
  tag: latest
  pullSecret: ghcr-secret

env:
  - name: "JAVA_OPTS"
    value: "-Dspring.profiles.active=test --enable-preview"
  - name: "LOGGING_LOGSTASH_HOST"
    value: "logstash.default.svc.cluster.local"
  - name: "LOGGING_LOGSTASH_PORT"
    value: "5044"

configs:
  - service-test-config

secrets:
  - service-test-secret

serviceAccount:
  create: true
  automount: false
  annotations: {}
  name: "helm-deployer"

service:
  fullname: "api-gw"
  type: ClusterIP
  port: 80
  serviceAccountName: "helm-deployer"

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: api-gw.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []


nameOverride: "api-gw"
fullnameOverride: "api-gw"

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
