replicaCount: 1

image:
  repository: ghcr.io/burakbalim/api-gw
  pullPolicy: Always
  tag: latest
  pullSecret: ghcr-secret

env:
  - name: "JAVA_OPTS"
    value: "-Dspring.profiles.active=test --enable-preview"

configs:
  - service-test-config

secrets:
  - service-test-secret

serviceAccount:
  create: true
  automount: false
  annotations: {}
  name: "helm-deployer"

service:
  fullname: "api-gw"
  type: ClusterIP
  port: 80
  serviceAccountName: "helm-deployer"

ingress:
  enabled: true
  customNamespace:
    enabled: true
    domain: "int.wordflashy.com"
  className: "nginx"
  defaultPath: "/gw"
  defaultPathType: "Prefix"
  annotations: {}
  tls: []

nameOverride: "api-gw"
fullnameOverride: "api-gw"

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

resources: {}
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
