replicaCount: 1

image:
  repository: ghcr.io/burakbalim/api-gw
  pullPolicy: IfNotPresent
  tag: latest
  pullSecret: ghcr-secret
  parameters: "-Dspring.profiles.active=dev --enable-preview"

secrets:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "o=a%!`@*hpib)3wg"
  GW_AUTHORIZATION_SECRET: ""

config:
  POSTGRES_HOST: "postgres-master.default.svc.cluster.local:5432"
  POSTGRES_POOL_SIZE: 10
  REDIS_HOST: ""
  REDIS_PORT: ""
  MONGO_HOST: ""
  MOUNTED_DIRECTORY: "/var/lib/api-gw/configuration/application"
  LOGSTASH_HOST: "logstash.default.svc.cluster.local"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  fullname: "api-gw"
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: api-gw.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

