secrets:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "o=a%!`@*hpib)3wg"
  GW_AUTHORIZATION_SECRET: ""

config:
  POSTGRES_HOST: "postgres-master.default.svc.cluster.local:5432"
  POSTGRES_POOL_SIZE: 10
  REDIS_HOST: ""
  REDIS_PORT: ""
  MONGO_HOST: ""
  MOUNTED_DIRECTORY: "/var/lib/api-gw/configuration/application/"
  LOGSTASH_HOST: "logstash.default.svc.cluster.local"
