architecture: replicaset
replicaCount: 1

image:
  repository: bitnami/mongodb
  tag: "6.0.10-debian-11-r0"

auth:
  enabled: true
  rootUser: admin
  rootPassword: mypassword
  username: user
  password: userpassword
  database: mydatabase

persistence:
  enabled: true
  name: "datadir"
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  mountPath: /bitnami/mongodb
  annotations: { }
  existingClaim: ""
  subPath: ""

resources:
  limits:
    memory: 512Mi
    cpu: 500m
  requests:
    memory: 256Mi
    cpu: 250m

arbiter:
  enabled: false  # Arbiter'i devre dışı bırakmak için 'false' olarak ayarlayın

mongodbDirectoryOverride: "/bitnami/mongodb"

livenessProbe:
  initialDelaySeconds: 60
  timeoutSeconds: 20

readinessProbe:
  initialDelaySeconds: 60
  timeoutSeconds: 20
