apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: elasticsearch-external
spec:
  hosts:
    - elasticsearch.external.local
  location: MESH_EXTERNAL
  ports:
    - number: 9200
      name: http
      protocol: HTTP
  resolution: DNS
