apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 9200
  type: {{ .Values.service.type }}
