apiVersion: batch/v1
kind: CronJob
metadata:
  name: velero-backup-pvc
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: velero-sa
          containers:
            - name: velero
              image: velero/velero:v1.11.0
              command:
                - sh
                - -c
                - |
                  # Önce mevcut yedeği sil (varsa)
                  /velero backup delete pvc-backup-prod --confirm
                  # Sonra yeni yedek oluştur
                  /velero backup create pvc-backup-prod --include-resources=persistentvolumeclaims,persistentvolumes --include-namespaces=staging
          restartPolicy: Never
