apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: velero
rules:
  - apiGroups: ["velero.io"]
    resources: ["backups", "restores", "schedules"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["namespaces", "pods", "persistentvolumeclaims"]
    verbs: ["get", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: velero-sa
  namespace: velero-backup-prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: velero-rolebinding
  namespace: velero
subjects:
  - kind: ServiceAccount
    name: velero-sa
    namespace: velero-backup-prod
roleRef:
  kind: ClusterRole
  name: velero
  apiGroup: rbac.authorization.k8s.io
