apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage-retain
provisioner: rancher.io/local-path
volumeBindingMode: Immediate  # veya bu satırı tamamen silebilirsin
reclaimPolicy: Retain
