replicaCount: 1

fullnameOverride: "postgres-slave"

image:
  repository: "postgres"
  tag: "15"

replicaSlot: "replica_1"

resources:
  requests:
    memory: "2Gi"
    cpu: "500m"
  limits:
    memory: "4Gi"
    cpu: "1000m"

storage:
  size: "100Gi"

service:
  type: "LoadBalancer"
