replicaCount: 1

image:
  repository: docker.elastic.co/logstash/logstash
  tag: "7.15.0"
  pullPolicy: IfNotPresent

service:
  name: logstash
  type: ClusterIP
  port: 5044

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

config:
  logstashConf: |
    input {
      tcp {
        port => 5044
        codec => json
        type => "json"
      }
    }

    filter {
      if [type] == "json" {
        json {
          source => "message"
        }
      }
    }

    output {
      elasticsearch {
        hosts => ["http://elasticsearch.default.svc.cluster.local:9200"]
        index => "logstash-%{+YYYY.MM.dd}"
      }
      stdout {
        codec => rubydebug
      }
    }
  logstashYml: |
    path.config: /usr/share/logstash/pipeline
    http.host: "0.0.0.0"
