clusterName: "k8s-logs"
replicaCount: 2

image:
  repository: "docker.elastic.co/elasticsearch/elasticsearch"
  tag: "7.16.3"

resources:
  requests:
    cpu: "100m"
  limits:
    cpu: "1000m"

storage:
  size: "1Gi"

env:
  ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  discoverySeedHosts: "es-cluster-0.elasticsearch"
  initialMasterNodes: "es-cluster-0"

service:
  type: "ClusterIP"
  port: 9200

ingress:
  enabled: true
  host: "elasticsearch.local"
