apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  PRIMARY_HOST: "postgres-master.default.svc.cluster.local"
  REPLICA_HOST: "postgres-slave.default.svc.cluster.local"
  postgresql.conf: |
    listen_addresses = '*'
    max_connections = 100
    shared_buffers = 128MB
    wal_level = replica
    max_wal_senders = 3
    max_replication_slots = 10
    wal_keep_size = 64MB
    hot_standby = on
  pg_hba.conf: |
    local   all             all                                    trust
    host    all             all             0.0.0.0/0              trust
    host    replication     postgres        0.0.0.0/0              trust
    host    api-gw          postgres        0.0.0.0/0              trust
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-master
spec:
  serviceName: postgres-master
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      role: master
  template:
    metadata:
      labels:
        app: postgres
        role: master
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: postgres
          image: postgres:15
          securityContext:
            runAsUser: 999
            runAsGroup: 999
          command:
            - sh
            - -c
            - |
              cp -f /etc/postgresql/postgresql.conf /var/lib/postgresql/data/postgresql.conf
              cp -f /etc/postgresql/pg_hba.conf /var/lib/postgresql/data/pg_hba.conf
              chmod 600 /var/lib/postgresql/data/postgresql.conf
              chmod 600 /var/lib/postgresql/data/pg_hba.conf
              exec postgres
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
            - name: PRIMARY_HOST
              value: "postgres-master.default.svc.cluster.local"
            - name: REPLICA_HOST
              value: "postgres-slave.default.svc.cluster.local"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-master-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-config-volume
              mountPath: /etc/postgresql/postgresql.conf
              subPath: postgresql.conf
            - name: postgres-config-volume
              mountPath: /etc/postgresql/pg_hba.conf
              subPath: pg_hba.conf
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "1000m"
      volumes:
        - name: postgres-config-volume
          configMap:
            name: postgres-config
  volumeClaimTemplates:
    - metadata:
        name: postgres-master-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-master
spec:
  selector:
    app: postgres
    role: master
  ports:
    - port: 5432
      targetPort: 5432
  type: LoadBalancer
