apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services-postgres-slave
  namespace: ingress-nginx
data:
  "5432": "default/postgres-slave:5432"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services-postgres-master
  namespace: ingress-nginx
data:
  "5432": "default/postgres-master:5432"

