replicaCount: 1

image:
  repository: ghcr.io/burakbalim/word-flashy-service
  pullPolicy: Always
  tag: latest
  pullSecret: ghcr-secret

env:
  - name: "JAVA_OPTS"
    value: "-Dspring.profiles.active=test"

configs:
  - service-test-config

secrets:
  - service-test-secret

serviceAccount:
  create: true
  automount: false
  annotations: {}
  name: "word-flashy-service"

service:
  fullname: "word-flashy-service"
  type: ClusterIP
  port: 80
  serviceAccountName: "word-flashy-service"

ingress:
  enabled: true
  customNamespace:
    enabled: true
    domain: "int.wordflashy.com"
  className: "nginx"
  defaultPath: "/word-flashy-service"
  defaultPathType: "Prefix"
  annotations: {}
  tls: []


nameOverride: "word-flashy-service"
fullnameOverride: "word-flashy-service"

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

resources: {}
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
