apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
  namespace: {{ .Release.Namespace }}
data:
  logstash.conf: |-
    {{ .Values.config.logstashConf | nindent 4 }}
  logstash.yml: |-
    {{ .Values.config.logstashYml | nindent 4 }}
