apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: logstash
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5044
