apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres-slave.fullname" . }}-config
data:
  PRIMARY_HOST: "{{ .Values.primaryHost }}"
  REPLICA_HOST: "{{ .Values.replicaHost }}"
  postgresql.conf: |
    hot_standby = on
  pg_hba.conf: |
    local   all             all                                    trust
    host    all             all             0.0.0.0/0              md5
