apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres-slave.fullname" . }}-config
data:
  PRIMARY_HOST: "{{ include "postgres.primaryHost" . }}"
  REPLICA_HOST: "{{ include "postgres.replicaHost" . }}"
  postgresql.conf: |
    hot_standby = on
  pg_hba.conf: |
    local   all             all                                    trust
    host    all             all             0.0.0.0/0              md5
