apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-slave.fullname" . }}
spec:
  selector:
    app: postgres
    role: slave
  ports:
    - port: 5432
      targetPort: 5432
  type: {{ .Values.service.type }}
  allocateLoadBalancerNodePorts: false
