namespace: default
replicaCount: 1

fullnameOverride: grafana

image:
  repository: grafana/grafana
  tag: latest

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

ingress:
  host: grafana.local
