replicaCount: 1

image:
  repository: prom/prometheus
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9090

ingress:
  enabled: true
  host: prometheus.local
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"

config:
  scrape_interval: 15s
  job_name: prometheus
  targets:
    - "localhost:9090"

