apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "config.fullname" . }}-config
data:
  POSTGRES_HOST: {{ .Values.config.POSTGRES_HOST | quote }}
  POSTGRES_POOL_SIZE: {{ .Values.config.POSTGRES_POOL_SIZE | quote }}
  REDIS_HOST: {{ .Values.config.REDIS_HOST | quote }}
  REDIS_PORT: {{ .Values.config.REDIS_PORT | quote }}
  MONGO_HOST: {{ .Values.config.MONGO_HOST | quote }}
  MOUNTED_DIRECTORY: {{ .Values.config.MOUNTED_DIRECTORY | quote }}
  LOGSTASH_HOST: {{ .Values.config.LOGSTASH_HOST | quote }}

