apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "config.fullname" . }}-config
data:
  POSTGRES_HOST: "postgres.{{ .Release.Namespace }}.svc.cluster.local:5432"
  MONGO_HOST: "mongo.{{ .Release.Namespace }}.svc.cluster.local"
  LOGSTASH_HOST: "logstash.{{ .Release.Namespace }}.svc.cluster.local"
  NOTIFICATION_SERVICE_URL: "notification-service.{{ .Release.Namespace }}.svc.cluster.local"
  OAUTH_USER_RESOURCE_URL: "user-resource-service.{{ .Release.Namespace }}.svc.cluster.local"
  POSTGRES_POOL_SIZE: {{ .Values.config.POSTGRES_POOL_SIZE | quote }}
  REDIS_HOST: "redis-master.{{ .Release.Namespace }}.svc.cluster.local"
  REDIS_PORT: "6379"
  MOUNTED_DIRECTORY: {{ .Values.config.MOUNTED_DIRECTORY | quote }}
  DOMAIN: {{ .Values.config.DOMAIN | quote }}

