apiVersion: v1
kind: Secret
metadata:
  name: {{ include "config.fullname" . }}-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secrets.POSTGRES_USER | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | b64enc }}
  GW_AUTHORIZATION_SECRET: {{ .Values.secrets.GW_AUTHORIZATION_SECRET | b64enc }}
#TODO Add alternative secrets for cloud provider
