replicas: 1

fullnameOverride: "postgres"

image:
  repository: postgres
  tag: "15"

service:
  type: ClusterIP

storage:
  useExistingClaim: true
  #existingClaim: postgres-data-postgres-0
  size: 10Gi
  storageClass: local-storage-delete

postgresqlConfig:
  listen_addresses = '*'
  max_connections = 100
  shared_buffers = 128MB
  wal_level = replica
  max_wal_senders = 3
  max_replication_slots = 10
  wal_keep_size = 64MB
  hot_standby = on

pgHbaConfig:
  local   all             all                                    trust
  host    all             all             0.0.0.0/0              trust
  host    replication     postgres        0.0.0.0/0              trust

